### ISSUE TITLE
WorldEdit checklist

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#576]
Various API additions that are needed to make WorldEdit work:

- [ ] Allow generating a single tree at a single location. #573
- [ ] Allow regenerating a single chunk #574
- [x] Be able to set/check a can fly ability #575

This list will probably be updated as I go through implementing WE.

**Comment by MattBDev** [comment]
I think that the Value API #685 needs to be added to this in order to implement schematic support and a few other crucial features into WorldEdit

**Comment by modwizcode** [comment]
WorldEdit needs this issue too. https://github.com/SpongePowered/SpongeAPI/issues/738

**Comment by Zidane** [comment]
@wizjany

This will affect you to.

**Comment by Zidane** [comment]
Closing this as we have separate issues, no need for this one too.
